language: generic

dist: bionic

## Uncomment the following lines if you require extra dependencies
#before_install:
# - sudo apt-get install ghostscript # If you use latex > dvips > ps2pdf
# - sudo apt-get install python-pygments # If you use the minted package
  # If you use custom fonts:
# - mkdir $HOME/.fonts
# - cp -a $TRAVIS_BUILD_DIR/src/fonts/. $HOME/.fonts/
# - fc-cache -f -v
     
install:
  - source ./texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

# Change working directory so including files will work
before_script:
  - cd $TRAVIS_BUILD_DIR/src/
script:
  # Texliveonfly will download packages automatically
  - texliveonfly book.tex
  # You can use latexmk to automatically handle bibtex and references (recommended)
  #- latexmk -pdf book.tex
  - pdflatex -synctex=1 -interaction=nonstopmode book.tex > custom_log.log
  - cat custom_log.log
  - cat custom_log.log | grep -E 'at\s*line(s|)\s*[0-9]+' > custom_errors.log || true
  - $TRAVIS_BUILD_DIR/script/check_emptiness_of_custom_errors_log.sh # fails on any warning in latex.
  - cat custom_errors.log
  - cp book.pdf $TRAVIS_BUILD_DIR/build/
  - curl -H "Authorization: token ${GITHUB_TOKEN}"
#  - curl -H "Authorization: token ${GITHUB_TOKEN}" -X POST -d "{\"body\": \"Hello world\"}" "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/issues/${TRAVIS_PULL_REQUEST}/comments"
  - $TRAVIS_BUILD_DIR/script/conditional_deploy_artifact.sh

  # But you could use any other compiler as well instead of latexmk. Example:
#  - pdflatex main.tex
#  - bibtex main
#  - pdflatex main.tex
#  - pdflatex main.tex # Compile twice to fix references

  # You can also pass arguments to texliveonfly:
#  - texliveonfly --arguments='-shell-escape' main.tex

## Uncomment the following lines to see the packages installed in travis
#after_script:
#  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
#  - tlmgr list --only-installed | grep -oP 'i \K.+?(?=:)'

deploy:
    provider: pages
    skip_cleanup: true
    token: $GH_REPO_TOKEN
    keep_history: true
    local_dir: build
    target_branch: gh-pages
    on :
        branch: master
